### ISSUE TITLE
When trying to link the package 'react-native link mobile-center-analytics' it says `Error: Cannot find module './Podfile'`

### ISSUE THREAD

**Issue by THPubs** [Microsoft/mobile-center-sdk-react-native#23]
When I try to link the package to the project I get the following error:

    module.js:472
        throw err;
        ^

    Error: Cannot find module './Podfile'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/home/pubudu/Projects/recruitx_mobile/node_modules/mobile-center-link-scripts/src/ios/index.js:14:15)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
    /home/pubudu/Projects/recruitx_mobile/node_modules/react-native/local-cli/core/makeCommand.js:19
            throw new Error(`Error occured during executing "${ command }" command`);
            ^

    Error: Error occured during executing "node node_modules/mobile-center-analytics/scripts/prelink" command
        at ChildProcess.prelink (/home/pubudu/Projects/recruitx_mobile/node_modules/react-native/local-cli/core/makeCommand.js:19:15)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at maybeClose (internal/child_process.js:885:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Any idea why?

**Comment by BretJohnson** [comment]
Is your file system case sensitive by chance, either Linux or a Mac formatted case sensitive (which you can verify with http://apple.stackexchange.com/questions/71357/how-to-check-if-my-hd-is-case-sensitive-or-not) ?

**Comment by THPubs** [comment]
Yeap it's case sensitive. Linux ext4.

**Comment by BretJohnson** [comment]
OK, good. I'm actually about to fix that issue, deploying an update in a couple hours with a fix. I'll mark the issue fixed then & you can verify.

**Comment by THPubs** [comment]
Perfect thanks :smile:

**Comment by BretJohnson** [comment]
Actually, I'll update in the morning. There's one other fix I want to get in too.

**Comment by THPubs** [comment]
Ah ok no issue. Thanks!

**Comment by THPubs** [comment]
Hi, will you be doing the update today?

**Comment by BretJohnson** [comment]
Sorry, it was delayed again, but yes, I will be updating later today. In the meantime you can workaround the issue by just editing `node_modules/mobile-center-link-scripts/src/ios/index.js` and changing the `require('./Podfile');` on line 14 to `require('./PodFile');`

**Comment by THPubs** [comment]
Ah cool! I will try to wait for the release. If get further delayed I will try the hack :-)

**Comment by BretJohnson** [comment]
@THPubs The update is available now, with this and a few other changes. Holler if you run into any issues.

**Comment by THPubs** [comment]
Great! Just tested and it's working perfectly! Thanks!
